### ISSUE TITLE
Cookies problem

### ISSUE THREAD

**Issue by alexgalvagno** [kanekotic/oauth-electron-facebook#2]
The webview that show facebook login form require cookies. How can I disable cookies?

**Comment by alvarolorentedev** [comment]
hello sorry for the late reply...can you give me steps to reproduce your issue? You want to disable for certain specific reason?
In this case the cookies handling is internal to the page loaded on the redirect of the oauth i am not doing any special handling of cookies, i can check if i could add an extra configuration so the navigation window can disable cookies but you should be able to do this before passing the window to the oauth component.

**Comment by alvarolorentedev** [comment]
closing due no response
