### ISSUE TITLE
Oauth not working correctly

### ISSUE THREAD

**Issue by jorgev259** [kanekotic/oauth-electron-facebook#3]
```
const authFB = require('oauth-electron-facebook')

      let info = {
        key: 'id here',
        secret: 'secret here',
        scope: ['manage_pages', 'publish_pages']
      }

      authFB.login(info, window).then(access => {
        console.log(access)
      }).catch(e => console.log(e))
        .finally(() => console.log('asdkms'))
```

None of the console.log trigger, also the window is redirected to a blank chromeerror url after logging in. Looking at the facebook oauth url i saw it uses http://localhost/ altho Facebook forces https for redirect urls (possible cause?)

**Comment by alvarolorentedev** [comment]
uhmm, dont think soo I have just tried it. 
I think there is a change on the API from facebook and the configuration I had a few days ago does not work anymore. My integration tests is failing now, because is not showing the page where user allows application to list of permissions.
I will try to solve this hopefully today, need to go through the docs to see what changed :)

**Comment by jorgev259** [comment]
```
window.loadURL(`https://www.facebook.com/v3.1/dialog/oauth?client_id=357529044987864&redirect_uri=https://www.facebook.com/connect/login_success.html&scope=manage_pages,publish_pages`)

      window.webContents.on('did-finish-load', async function () {
        try {
if (!window.webContents.getURL().startsWith('https://www.facebook.com/connect/login_success.html')) return
          let query = url.parse(window.webContents.getURL(), true).query
          FB.api('oauth/access_token', {
            client_id: 'id',
            client_secret: 'secret',
            redirect_uri: 'https://www.facebook.com/connect/login_success.html',
            code: query.code
          }, function (res) {
            console.log('here')
            if (!res || res.error) {
              console.log(!res ? 'error occurred' : res.error)
              return
            }

            var accessToken = res.access_token
            console.log(res)
            var expires = res.expires_in ? res.expires : 0
            console.log(accessToken)
          })
        } catch (e) {
          reject(e)
        }
      })
```
This is the solution im currently using, maybe its that you now have to use the success url that facebook suggests.

**Comment by jorgev259** [comment]
(slight edit)

**Comment by alvarolorentedev** [comment]
so I will document better but it works for me with the next settings:
![screen shot 2018-10-22 at 09 27 14](https://user-images.githubusercontent.com/3071208/47281826-203a9900-d5dd-11e8-9ff2-ed11552eeb0e.png)
![screen shot 2018-10-22 at 09 27 25](https://user-images.githubusercontent.com/3071208/47281832-292b6a80-d5dd-11e8-918f-fa17b4c26efb.png)
do you have any special or simpler setting?

**Comment by kanekotic** [comment]
so I will document better but it works for me with the next settings:
![screen shot 2018-10-22 at 09 27 14](https://user-images.githubusercontent.com/3071208/47281826-203a9900-d5dd-11e8-9ff2-ed11552eeb0e.png)
![screen shot 2018-10-22 at 09 27 25](https://user-images.githubusercontent.com/3071208/47281832-292b6a80-d5dd-11e8-918f-fa17b4c26efb.png)
do you have any special or simpler setting?

**Comment by jorgev259** [comment]
Guess it was on my side, http://localhost is not allowd but localhost is

**Comment by jorgev259** [comment]
Further configurations would be appreciated

**Comment by alvarolorentedev** [comment]
updated documentation
